from collections.abc import Sequence

def hash(data: bytes) -> str: ...
def compare(left: str, right: str) -> int: ...

class Matcher:
    def __init__(self, fingerprint: str) -> None: ...
    def find_match(
        self, candidates: Sequence[str], *, threshold: int = 90
    ) -> tuple[int, int] | None: ...
